-- Supabase SQL Editor에서 1회 실행해 주세요.
create table if not exists public.m_favorite (
    id bigint generated by default as identity primary key,
    user_id varchar(20) not null,
    kind varchar(40) not null,
    job_key varchar(255) not null,
    job_title varchar(500),
    job_area varchar(200),
    job_link text,
    created_at timestamptz not null default now(),
    constraint m_favorite_user_job_unique unique (user_id, kind, job_key)
);

create index if not exists m_favorite_user_created_idx
    on public.m_favorite (user_id, created_at desc);

alter table public.m_favorite enable row level security;
